version: '3.7'

services:
  web:
    build:
      context: TradePlatform
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./TradePlatform/:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:12-alpine
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  celery:
    build:
      context: TradePlatform
      dockerfile: Dockerfile
    command: celery -A TradePlatform worker -l info
    volumes:
      - ./TradePlatform:/usr/src/app
    env_file:
      - ./backend.env
    depends_on:
      - db
      - redis
      - web

  celery-beat:
    build:
      context: TradePlatform
      dockerfile: Dockerfile
    command: celery -A TradePlatform beat -l info
    volumes:
      - ./TradePlatform:/usr/src/app
    env_file:
      - ./backend.env
    depends_on:
      - db
      - redis
      - web