# Generated by Django 3.2.8 on 2021-10-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
