# Generated by Django 3.2.8 on 2021-10-11 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='code',
        ),
    ]
