# Generated by Django 3.2.8 on 2021-10-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_auto_20211011_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='offer',
            name='order_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'buy'), ('2', 'sell')]),
        ),
    ]
