# Generated by Django 3.2.8 on 2021-10-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('trading', '0003_auto_20211011_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='entry_quantity',
            field=models.IntegerField(blank=True,
                                      null=True,
                                      verbose_name='Requested quantity'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='order_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'buy'),
                                                            (2, 'sell')]),
        ),
    ]
