# Generated by Django 3.2.8 on 2021-10-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_offer_current_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='currency',
        ),
    ]
